import assert from 'node:assert/strict';
import fs from 'node:fs';
import { chromium } from 'playwright';
import { PREAUTHORIZED_ADGUARD_CONTROL_SOURCE } from '../scripts/preauthorized_adguard_control.mjs';
const source = fs.readFileSync(new URL('../hotdeal-focus.user.js', import.meta.url), 'utf8');
const title = '[아빠새] 모바일 상품 정보';
const html = `<!doctype html><html><head><meta property="og:title" content="${title} - 패션정보 - 어미새"><meta property="og:type" content="article"></head><body><main id="bd"><div id="D_"><div class="_hd"><h2>국내 ${title}</h2></div><table class="et_vars"><tbody><tr><th>링크</th><td><a href="https://shop.invalid/product">https://shop.invalid/product</a></td></tr></tbody></table><article><div class="document_99000001_123 rhymix_content xe_content"><p><a href="https://shop.invalid/product">https://shop.invalid/product</a></p><p>상품 정보와 구매 링크를 그대로 보존하는 모바일 본문입니다.</p></div></article></div><div id="C_"><div class="_hd" id="comment"><span>댓글 <b>1</b></span></div><div class="_bd cf clear"><div id="comment_99000002" data-press-trigger="99000002" style="cursor:pointer;touch-action:pan-y;user-select:none" class="_comment p_rt cf re clear"><div class="content"><div class="user">작성자</div><div class="comment_99000002_123 rhymix_content xe_content">가격 괜찮은 상품들이 종종 보입니다.</div><a class="re_comment" href="/index.php?document_srl=99000001&act=dispBoardReplyComment&comment_srl=99000002">답글</a></div></div><div class="cmt-overlay-background" data-cmt-overlay="99000002" style="display:none"><div class="cmt-option"><div class="container"><a class="favorite" href="#">추천</a><a class="re_comment" href="/index.php?document_srl=99000001&act=dispBoardReplyComment&comment_srl=99000002">답글</a><a href="#" class="quit">닫기</a></div></div></div></div><div class="_hd _hdc"></div><center>게시판 공지와 광고</center><div class="_ft">댓글 쓰기 권한이 없습니다.</div></div><aside>인기글 추천글</aside></main></body></html>`;
const fixtureHtml = html.replace('<th>링크</th>', '<th>링크<i class="fas fa-question-circle tooltip"><span class="tooltiptext" style="visibility:hidden;position:absolute">어미새 커뮤니티 내 게시된 구매 링크는 제휴 링크로 전환되며, 이를 통해 어미새는 제휴사로부터 일정 비율의 커미션을 지급 받습니다.</span></i></th>').replace('style="display:none"', 'style="display:table;visibility:hidden;opacity:0;position:fixed;width:390px;height:176px;z-index:400888"');
const browser = await chromium.launch({headless:true});
try {
 const page = await browser.newPage({viewport:{width:390,height:844}});
 await page.setContent(fixtureHtml);
 const resolution = await page.evaluate(source => {
  const module={exports:{}};new Function('module',source)(module);
  const api=module.exports;const contract=api.SITE_CONTRACTS.find(s=>s.id==='eomisae');
  const exact=api.resolveDocument(document,contract.layouts,null);
  return {ok:exact.ok,role:exact.role,reason:exact.reason,error:exact.error};
 },source);
 assert.equal(resolution.ok,true,JSON.stringify(resolution));
 await page.close();
 const context=await browser.newContext({viewport:{width:390,height:844},isMobile:true});
 try {
  const page=await context.newPage();
  const nativeInitialization = `<script>document.addEventListener('DOMContentLoaded',()=>{document.documentElement.dataset.initialProjectionRaced=String(!!document.querySelector('#D_ [data-hotdeal-focus-keep]'));const container=document.querySelector('#comment_99000002 .content');const nativeWrapper=document.createElement('section');nativeWrapper.className='native-comment-wrapper';container.parentElement.append(nativeWrapper);nativeWrapper.append(container);});</script>`;
  await page.route('**/*',r=>r.fulfill({status:200,contentType:'text/html; charset=utf-8',body:fixtureHtml.replace('</body>',nativeInitialization+'</body>')}));
  await page.addInitScript(({source,control})=>{(0,eval)(control);(0,eval)(source);},{source,control:PREAUTHORIZED_ADGUARD_CONTROL_SOURCE});
  await page.goto('https://eomisae.co.kr/os/99000001');
  await page.waitForFunction(()=>globalThis.__HOTDEAL_FOCUS_DIAGNOSTICS__?.state==='ready'&&!document.documentElement.hasAttribute('data-hotdeal-focus-lock'),null,{timeout:5000});
  assert.equal(await page.locator('html').getAttribute('data-initial-projection-raced'),'false');
  assert.equal(await page.evaluate(()=>{const e=document.querySelector('.tooltip'),s=getComputedStyle(e);return !!e.getClientRects().length&&s.display!=='none'&&s.visibility==='visible';}),false);
  assert.equal(await page.locator('.et_vars a').getAttribute('href'),'https://shop.invalid/product');
  assert.match(await page.locator('article').innerText(),/모바일 본문/);
  assert.match(await page.locator('#comment_99000002').innerText(),/가격 괜찮은/);
  assert.equal(await page.evaluate(()=>getComputedStyle(document.querySelector('aside')).visibility),'hidden');
  await page.evaluate(() => {
   const paragraph=document.querySelector('#D_ article p');
   const existingLink=paragraph.querySelector('a');
   const wrapper=document.createElement('span');
   wrapper.className='publisher-native-wrapper';
   wrapper.append(existingLink);
   paragraph.append(wrapper);
  });
  await page.waitForTimeout(100);
  assert.equal(await page.evaluate(()=>globalThis.__HOTDEAL_FOCUS_DIAGNOSTICS__?.state),'ready',await page.evaluate(()=>JSON.stringify(globalThis.__HOTDEAL_FOCUS_DIAGNOSTICS__)));
  assert.match(await page.locator('#D_ article').innerText(),/모바일 본문/);
  await page.evaluate(() => {
   const clone=document.querySelector('#D_ article p a').cloneNode(true);
   const widget=document.createElement('aside');widget.id='publisher-clone-widget';
   widget.append(clone);document.body.append(widget);
  });
  await page.waitForTimeout(100);
  assert.equal(await page.evaluate(()=>globalThis.__HOTDEAL_FOCUS_DIAGNOSTICS__?.state),'ready');
  assert.equal(await page.locator('#publisher-clone-widget [data-hotdeal-focus-keep]').count(),0);
  assert.equal(await page.evaluate(()=>getComputedStyle(document.querySelector('#publisher-clone-widget')).visibility),'hidden');
  await page.close();
  const delayedPage=await context.newPage();
  const delayedBodyHtml=fixtureHtml.replace('<head>', '<head><style id="publisher-late-body">#D_ article > .rhymix_content { display:none; }</style>');
  await delayedPage.route('**/*',r=>r.fulfill({status:200,contentType:'text/html; charset=utf-8',body:delayedBodyHtml}));
  await delayedPage.addInitScript(({source,control})=>{
   globalThis.__preflightMeasurementCount=0;
   new MutationObserver(records=>{
    globalThis.__preflightMeasurementCount+=records.filter(record=>record.type==='attributes'&&record.attributeName==='data-hotdeal-focus-measure').length;
   }).observe(document,{subtree:true,attributes:true});
   (0,eval)(control);(0,eval)(source);
  },{source,control:PREAUTHORIZED_ADGUARD_CONTROL_SOURCE});
  await delayedPage.goto('https://eomisae.co.kr/os/99000001');
  await delayedPage.waitForTimeout(125);
  assert.equal(await delayedPage.locator('html').getAttribute('data-hotdeal-focus-lock'),null);
  assert.equal(await delayedPage.evaluate(()=>globalThis.__HOTDEAL_FOCUS_DIAGNOSTICS__?.state),'recovery');
  assert.equal(await delayedPage.evaluate(()=>getComputedStyle(document.querySelector('aside')).display),'none');
  const measurementCount=await delayedPage.evaluate(()=>globalThis.__preflightMeasurementCount);
  assert.ok(measurementCount<=8,`Preflight must not observe and retry its own visibility measurement: ${measurementCount}`);
  await delayedPage.evaluate(()=>document.querySelector('#publisher-late-body').remove());
  await delayedPage.waitForFunction(()=>document.documentElement.getAttribute('data-hotdeal-focus-state')==='ready'&&!document.documentElement.hasAttribute('data-hotdeal-focus-lock'),null,{timeout:5000});
  assert.match(await delayedPage.locator('#D_ article').innerText(),/모바일 본문/);
  await delayedPage.close();
  const emptyPage=await context.newPage();
  const unrelatedRows=[99000003,99000004,99000005].map(id=>`<tr><td class="title"><a href="/os/${id}">다른 상품 글</a><a href="/os/${id}#C_">댓글 2</a></td><td>작성자</td></tr>`).join('');
  const emptyCommentsHtml=fixtureHtml.replace(/<div id="C_">[\s\S]*?<aside>/,`<div id="C_"><div class="_hd" id="comment"><span>댓글 <b>0</b></span></div><br><center>게시판 공지와 광고</center><div class="_ft">댓글 쓰기 권한이 없습니다.</div></div><div id="L_"><div class="_hd">다른 게시글 목록 댓글순 제목 검색</div><div class="_bd"><table class="_listA"><tbody>${unrelatedRows}</tbody></table></div></div><aside>`);
  await emptyPage.route('**/*',r=>r.fulfill({status:200,contentType:'text/html; charset=utf-8',body:emptyCommentsHtml}));
  await emptyPage.addInitScript(({source,control})=>{(0,eval)(control);(0,eval)(source);},{source,control:PREAUTHORIZED_ADGUARD_CONTROL_SOURCE});
  await emptyPage.goto('https://eomisae.co.kr/os/99000001');
  await emptyPage.waitForFunction(()=>document.documentElement.getAttribute('data-hotdeal-focus-state')==='ready'&&!document.documentElement.hasAttribute('data-hotdeal-focus-lock'),null,{timeout:2500});
  assert.match(await emptyPage.locator('#D_ article').innerText(),/모바일 본문/);
  assert.equal(await emptyPage.locator('[data-hotdeal-focus-role="comment-item"]').count(),0);
  assert.equal(await emptyPage.evaluate(()=>getComputedStyle(document.querySelector('#L_')).visibility),'hidden');
  await emptyPage.close();
  const mobileListPage=await context.newPage();
  const mobileRows=[99000003,99000004,99000005].map(id=>`<div class="lst_nm"><div class="lst_wrap"><a class="title pjax" href="/os/${id}">다른 상품 글</a></div><div class="lst_reply_wrap"><div class="reply"><a href="/os/${id}#C_">2</a></div></div></div>`).join('');
  const imageUri='data:image/svg+xml,'+encodeURIComponent('<svg xmlns="http://www.w3.org/2000/svg" width="100" height="100"><rect width="100" height="100" fill="blue"/></svg>');
  const imageOnlyBody=`<p><a href="${imageUri}" style="width:100%;height:100%"><img src="${imageUri}" alt="상품 사진 1"></a></p><p><img src="${imageUri}" alt="상품 사진 2"></p><p>&nbsp;</p>`;
  const mobileEmptyHtml=emptyCommentsHtml.replace(`<table class="_listA"><tbody>${unrelatedRows}</tbody></table>`,`<div id="bd_lst" class="bd_lst">${mobileRows}</div>`).replace('<p><a href="https://shop.invalid/product">https://shop.invalid/product</a></p><p>상품 정보와 구매 링크를 그대로 보존하는 모바일 본문입니다.</p>',imageOnlyBody).replace('<article>','<article><div class="vote _ft"><button>추천 6</button><button>샀어요 2</button><button>스크랩</button></div>');
  await mobileListPage.route('**/*',r=>r.fulfill({status:200,contentType:'text/html; charset=utf-8',body:mobileEmptyHtml}));
  await mobileListPage.addInitScript(({source,control})=>{(0,eval)(control);(0,eval)(source);},{source,control:PREAUTHORIZED_ADGUARD_CONTROL_SOURCE});
  await mobileListPage.goto('https://eomisae.co.kr/os/99000001');
  await mobileListPage.waitForFunction(()=>document.documentElement.getAttribute('data-hotdeal-focus-state')==='ready'&&!document.documentElement.hasAttribute('data-hotdeal-focus-lock'),null,{timeout:2500});
  assert.equal(await mobileListPage.locator('[data-hotdeal-focus-role="body"]').evaluate(e=>e.tagName),'DIV');
  assert.equal(await mobileListPage.evaluate(()=>getComputedStyle(document.querySelector('.vote')).visibility),'hidden');
  assert.equal(await mobileListPage.locator('[data-hotdeal-focus-role="body"] img').count(),2);
  assert.equal(await mobileListPage.locator('.et_vars a').getAttribute('href'),'https://shop.invalid/product');
  await mobileListPage.close();
  const navigationPage=await context.newPage();
  const nativeMenuScript=`<script>document.addEventListener('DOMContentLoaded',()=>{const menu=document.querySelector('[data-cmt-overlay]');document.querySelector('[data-press-trigger]').addEventListener('click',()=>{menu.style.visibility='visible';menu.style.opacity='1';});menu.querySelector('.quit').addEventListener('click',event=>{event.preventDefault();menu.style.visibility='hidden';menu.style.opacity='0';});});</script>`;
  const navigationHtml=fixtureHtml.replace('<head>', '<head><meta name="viewport" content="width=device-width,initial-scale=1"><style>.document_99000001_123{min-height:1800px}html{scroll-behavior:smooth}.cmt-option{width:100%;height:100%}</style>').replace('width:390px;height:176px;', 'inset:0;width:100vw;height:100vh;').replace('</body>',nativeMenuScript+'</body>');
  await navigationPage.route('**/*',r=>r.fulfill({status:200,contentType:'text/html; charset=utf-8',body:navigationHtml}));
  await navigationPage.addInitScript(({source,control})=>{(0,eval)(control);(0,eval)(source);},{source,control:PREAUTHORIZED_ADGUARD_CONTROL_SOURCE});
  await navigationPage.goto('https://eomisae.co.kr/os/99000001');
  await navigationPage.waitForFunction(()=>document.documentElement.getAttribute('data-hotdeal-focus-state')==='ready'&&!document.documentElement.hasAttribute('data-hotdeal-focus-lock'),null,{timeout:5000});
  const navigation=navigationPage.getByRole('navigation',{name:'핫딜 읽기 도구'});
  assert.equal(await navigation.getByRole('button',{name:'댓글',exact:true}).evaluate(button=>{
   const rect=button.getBoundingClientRect();
   return document.elementFromPoint(rect.x+rect.width/2,rect.y+rect.height/2)===button;
  }),true,'A closed native comment overlay must not intercept reader navigation clicks');
  await navigation.getByRole('button',{name:'댓글',exact:true}).click();
  await navigationPage.waitForFunction(()=>window.scrollY>500&&document.querySelector('#comment_99000002').getBoundingClientRect().top<window.innerHeight,null,{timeout:1500});
  assert.equal(await navigationPage.locator('#comment_99000002').getAttribute('data-hotdeal-focus-role'),'comment-item');
  await navigationPage.locator('#comment_99000002 .comment_99000002_123').click();
  await navigationPage.waitForFunction(()=>getComputedStyle(document.querySelector('.cmt-overlay-background')).visibility==='visible',null,{timeout:1500}).catch(async error=>{throw new Error(JSON.stringify(await navigationPage.evaluate(()=>({diagnostics:globalThis.__HOTDEAL_FOCUS_DIAGNOSTICS__,menu:document.querySelector('.cmt-overlay-background').outerHTML}))),{cause:error});});
  assert.equal(await navigationPage.locator('html').getAttribute('data-hotdeal-focus-state'),'ready');
  assert.doesNotMatch(await navigationPage.evaluate(()=>globalThis.__HOTDEAL_FOCUS_DIAGNOSTICS__.targetReason),/^frozen-/);
  await navigationPage.locator('.cmt-overlay-background .quit').click();
  await navigationPage.waitForFunction(()=>getComputedStyle(document.querySelector('.cmt-option')).pointerEvents==='none',null,{timeout:1500}).catch(async error=>{throw new Error(JSON.stringify(await navigationPage.evaluate(()=>({diagnostics:globalThis.__HOTDEAL_FOCUS_DIAGNOSTICS__,menu:document.querySelector('.cmt-overlay-background').outerHTML}))),{cause:error});});
  assert.doesNotMatch(await navigationPage.evaluate(()=>globalThis.__HOTDEAL_FOCUS_DIAGNOSTICS__.targetReason),/^frozen-/);
  await navigation.getByRole('button',{name:'본문',exact:true}).click();
  await navigationPage.waitForFunction(()=>Math.abs(document.querySelector('[data-hotdeal-focus-role="product"]').getBoundingClientRect().top)<2,null,{timeout:1500});
  assert.equal(new URL(navigationPage.url()).hash,'');
  assert.equal(await navigationPage.locator('#D_ article a').evaluate(link=>{
   const rect=link.getBoundingClientRect();
   return document.elementFromPoint(rect.x+rect.width/2,rect.y+rect.height/2)===link;
  }),true,'Closing the native menu must restore pointer access to the original purchase link');
  await navigationPage.close();
 } finally {await context.close();}
} finally {await browser.close();}
console.log('Eomisae mobile comment context menu and original body regression passed');
