#!/usr/bin/env python3
"""Build the stable marker-only AdGuard gate consumed by the userscript."""

from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import Any, Iterable, Mapping, Sequence

from build_filter import (
    ConfigError,
    DEFAULT_CONFIG_PATH,
    PROJECT_ROOT,
    check_filter,
    load_config,
    write_filter,
)


DEFAULT_OUTPUT_PATH = PROJECT_ROOT / "dist" / "filter.txt"
PROTOCOL_VERSION = "1"
GENERATOR_VERSION = "0.3.6"
GATE_ARTIFACT_VERSION = "1.0.0"
GATE_GENERATOR_VERSION = "1.0.0"
READY_ATTRIBUTE = "data-hotdeal-focus-ready"
KEEP_ATTRIBUTE = "data-hotdeal-focus-keep"
LOCK_ATTRIBUTE = "data-hotdeal-focus-lock"
PROTOCOL_ATTRIBUTE = "data-hotdeal-focus-protocol"
STATE_ATTRIBUTE = "data-hotdeal-focus-state"
TOP_LAYER_PAINT_TARGETS = ("dialog", "[popover]", ":fullscreen")
PAINT_LOCK_DECLARATIONS = (
    "transition: none !important; "
    "animation: none !important; "
    "content-visibility: hidden !important; "
    "visibility: hidden !important; "
    "opacity: 0 !important; "
    "pointer-events: none !important; "
    "clip-path: inset(50%) !important;"
)


def paint_lock_selectors(root_selector: str) -> tuple[str, ...]:
    selectors = [root_selector]
    for target in TOP_LAYER_PAINT_TARGETS:
        selectors.append(f"{root_selector} {target}")
        selectors.append(f"{root_selector} {target}::backdrop")
    return tuple(selectors)


def build_gate_rules(domain: str) -> tuple[str, str]:
    scope = f"[$domain={domain}]"
    protocol_ready = (
        f'[{READY_ATTRIBUTE}="1"]'
        f'[{PROTOCOL_ATTRIBUTE}="{PROTOCOL_VERSION}"]'
        f'[{STATE_ATTRIBUTE}="ready"]'
    )
    unready_root = f"html:not({protocol_ready})"
    runtime_locked_root = f'html[{LOCK_ATTRIBUTE}="1"]'
    lock_selectors = paint_lock_selectors(unready_root) + paint_lock_selectors(
        runtime_locked_root
    )
    lock_rule = f"{scope}#$#{', '.join(lock_selectors)} {{ {PAINT_LOCK_DECLARATIONS} }}"
    projection_rule = (
        f"{scope}#?#html{protocol_ready} body *:not([{KEEP_ATTRIBUTE}])"
    )
    return lock_rule, projection_rule


def iter_gate_rules(
    config: Mapping[str, Any],
) -> Iterable[tuple[str, str, str, str]]:
    for site in sorted(config["sites"], key=lambda item: item["id"]):
        domains = sorted({layout["domain"] for layout in site["layouts"]})
        for domain in domains:
            lock_rule, projection_rule = build_gate_rules(domain)
            yield site["name"], "domain-gate", domain, lock_rule
            yield site["name"], "domain-gate", domain, projection_rule


def render_gate_filter(config: Mapping[str, Any]) -> str:
    metadata = config["metadata"]
    lines = [
        f"! Title: {metadata['title']} Marker Gate",
        "! Description: Fail-closed protocol gate for the Hotdeal Focus userscript.",
        f"! Version: {GATE_ARTIFACT_VERSION}",
        f"! Expires: {metadata['expires_hours']} hours",
        f"! License: {metadata['license']}",
        f"! Hotdeal-Focus-Protocol: {PROTOCOL_VERSION}",
        f"! Generator-Version: {GATE_GENERATOR_VERSION}",
        "! Generated by scripts/build_gate_filter.py. Do not edit this file directly.",
        "!",
    ]
    seen: set[str] = set()
    last_context: tuple[str, str, str] | None = None
    for site_name, layout_id, domain, rule in iter_gate_rules(config):
        context = (site_name, layout_id, domain)
        if context != last_context:
            lines.append(f"! {site_name} / {layout_id} / {domain}")
            last_context = context
        if rule in seen:
            raise ConfigError(f"duplicate generated gate rule: {rule}")
        seen.add(rule)
        lines.append(rule)
    return "\n".join(lines) + "\n"


def parse_arguments(arguments: Sequence[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Build the marker-only AdGuard Hotdeal Focus gate filter."
    )
    parser.add_argument("--config", type=Path, default=DEFAULT_CONFIG_PATH)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT_PATH)
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--stdout", action="store_true")
    return parser.parse_args(arguments)


def main(arguments: Sequence[str] | None = None) -> int:
    options = parse_arguments(arguments)
    try:
        config = load_config(options.config)
        rendered = render_gate_filter(config)
    except ConfigError as error:
        print(f"configuration error: {error}", file=sys.stderr)
        return 2
    if options.stdout:
        sys.stdout.write(rendered)
        return 0
    if options.check:
        if check_filter(options.output, rendered):
            print(f"up to date: {options.output}")
            return 0
        print(f"out of date: {options.output}", file=sys.stderr)
        return 1
    write_filter(options.output, rendered)
    rule_count = sum(1 for _ in iter_gate_rules(config))
    print(f"built {rule_count} marker-gate rules: {options.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
